[package]
name = "rust_service"
version = "0.1.1"
authors = ["Chris <https://github.com/electronicsleep>"]
edition = "2018"

[dependencies]
actix = "0.12.0"
actix-web = "4.0.1"
serde = {version = "1.0.106", features = ["derive"]}
mysql = "21.0.1"

[profile.dev]
opt-level = 0

[profile.release.package."*"]
codegen-units = 1
opt-level = 3

[profile.release]
opt-level = 3
lto = true
